name = "cloudflare-deployment-migration"
account_id = "366d25e255055a4f4853f19b2be0ce28"
main = ".open-next/worker.js"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
CLOUDFLARE_BINDINGS = "1"
ADMIN_EMAIL = "fikruamen11@gmail.com"
NEXT_PUBLIC_SITE_URL = "https://cloudflare-deployment-migration.fikruamen11.workers.dev"
CLOUDINARY_CLOUD_NAME = "dlaaccona"
CLOUDINARY_API_KEY = "159474719226525"
CLOUDINARY_FOLDER = "ephikorea/products"

[observability.logs]
enabled = false
invocation_logs = true

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "cloudflare-deployment-migration"

[[d1_databases]]
binding = "DB"
database_name = "ephikorea"
database_id = "d8263833-5c7b-4031-ba24-55d389b6f42f"
